// <auto-generated />
namespace Manager_Employee.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Intial_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intial_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231807478_Intial_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
