// <auto-generated />
namespace Manager_Employee.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Start_Dateupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Start_Dateupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201701271421440_Start_Date update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
